- name: Mise à jour des paquets
  ansible.builtin.apt:
    update_cache: true

- name: Installation des paquets prérequis
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Créer le répertoire pour les clés GPG d'APT
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Télécharger la clé GPG officielle de Docker
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: 'a+r'

- name: Ajouter le dépôt Docker au format DEB822
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: ["https://download.docker.com/linux/debian"]
    suites: ["{{ ansible_distribution_release }}"]
    components: [stable]
    architectures: ["{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"]
    signed_by: /etc/apt/keyrings/docker.asc
    state: present

- name: Installer les paquets Docker officiels
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Vérification de fonctionnement Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Ajouter les utilisateurs au groupe docker
  ansible.builtin.user:
    name: jenkins
    groups: docker
    append: yes