Vagrant.configure("2") do |config|
  
  config.vm.box = "generic/debian12"

  # Configuration globale
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 2048
    libvirt.cpus = 2
  end

  # Serveur code-prod-fr-01
  config.vm.define "codeprod" do |codeprod|
    codeprod.vm.hostname = "code-prod-fr-01"
    codeprod.vm.network "private_network", ip: "10.10.45.20"
    codeprod.vm.provision "ansible" do |ansible|
      ansible.playbook = "./ansible/playbooks/deploy_env-code.yml"
      ansible.inventory_path = "./ansible/inventories"
      ansible.limit = "code-prod"
      ansible.galaxy_roles_path = "./ansible/roles"
    end
  end

  # Serveur ci-prod-fr-01
  config.vm.define "ciprod" do |ciprod|
    ciprod.vm.hostname = "ci-prod-fr-01"
    ciprod.vm.network "private_network", ip: "10.10.45.21"
    ciprod.vm.provision "ansible" do |ansible|
      ansible.playbook = "./ansible/playbooks/deploy_env-ci.yml"
      ansible.inventory_path = "./ansible/inventories"
      ansible.limit = "ci-jenkins-prod"
      ansible.galaxy_roles_path = "./ansible/roles"
    end
  end

  # Serveur web-dev-fr-01
  config.vm.define "webdev" do |webdev|
    webdev.vm.hostname = "web-dev-fr-01"
    webdev.vm.network "private_network", ip: "10.10.45.10"
    webdev.vm.provision "ansible" do |ansible|
      ansible.playbook = "./ansible/playbooks/deploy_env-web.yml"
      ansible.inventory_path = "./ansible/inventories"
      ansible.limit = "web-dev"
      ansible.galaxy_roles_path = "./ansible/roles"
    end
  end

  # Serveur web-prod-fr-01
  config.vm.define "webprod" do |webprod|
    webprod.vm.hostname = "web-prod-fr-01"
    webprod.vm.network "private_network", ip: "10.10.45.30"
    webprod.vm.provision "ansible" do |ansible|
      ansible.playbook = "./ansible/playbooks/deploy_env-web.yml"
      ansible.inventory_path = "./ansible/inventories"
      ansible.limit = "web-prod"
      ansible.galaxy_roles_path = "./ansible/roles"
    end
  end
end