---

- name: Créer l'utilisateur de déploiement
  ansible.builtin.user:
    name: jenkins
    shell: /bin/bash

- name: Ajout de l'utilisateur jenkins au groupe Docker
  ansible.builtin.user:
    name: jenkins
    groups: docker
    append: yes

- name: Déposer la clé SSH publique pour le Maître Jenkins
  ansible.posix.authorized_key:
    user: jenkins
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG95Ri8NjGbTgA0v6/9uQCsS84EQO7VwxlDtNi9WRPHB jenkins"